#!/usr/bin/env python3
"""
Build the MECH 2030 lecture-notes website.

  python build_site.py            # compile everything into ./site
  python build_site.py --no-pdf   # rebuild only index.html (fast preview)

Steps:
  1. Find every lectures/wXXlY.tex that is not marked "% draft".
  2. Compile each one to its own PDF.
  3. Generate and compile full_notes.tex (all published lectures + contents).
  4. Write site/index.html linking to everything, grouped by week.

The GitHub Action in .github/workflows/publish.yml runs this script on every
push and publishes the ./site folder to GitHub Pages.
"""

import datetime as dt
import html
import re
import shutil
import subprocess
import sys
from pathlib import Path

# ----------------------------------------------------------------------
# Course settings -- edit these
# ----------------------------------------------------------------------
COURSE_CODE = "MECH 2030"
COURSE_TITLE = "Solid Mechanics"
INSTRUCTOR = "Prof. Eric M. Stewart"
AFFILIATION = "University of Cincinnati"
DEPARTMENT = "Mechanical, Materials, and Industrial Engineering"
TERM = "Fall 2026"
INTRO = ("Typeset lecture notes, posted soon after each class. ")
DISCLAIMER = ( "I use Claude to convert my hand-written lecture notes to typeset PDFs after each lecture. "
         "I check each typeset PDF for accuracy, but errors are still possible. Please email me about any issues you find (eric.stewart AT uc.edu).")

# ----------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent
LECTURE_DIR = ROOT / "lectures"
BUILD_DIR = ROOT / "build"
SITE_DIR = ROOT / "site"
PDF_DIR = SITE_DIR / "pdf"

LECTURE_RE = re.compile(r"\\lecture\{(\d+)\}\{(\d+)\}\{(.*)\}")
DRAFT_RE = re.compile(r"^\s*%\s*draft\s*$", re.IGNORECASE | re.MULTILINE)
POSTED_RE = re.compile(r"^\s*%\s*posted:\s*(\d{4}-\d{2}-\d{2})\s*$", re.MULTILINE)


def git_added_date(path: Path):
    """Date the file was first committed (None outside a git repo)."""
    try:
        out = subprocess.run(
            ["git", "log", "--diff-filter=A", "--follow", "--format=%as", "--", str(path)],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.split()
        return dt.date.fromisoformat(out[-1]) if out else None
    except (subprocess.CalledProcessError, FileNotFoundError, ValueError):
        return None


def find_lectures():
    lectures = []
    for path in sorted(LECTURE_DIR.glob("*.tex")):
        text = path.read_text(encoding="utf-8")
        match = LECTURE_RE.search(text)
        if not match:
            print(f"  skipping {path.name}: no \\lecture{{..}}{{..}}{{..}} line")
            continue
        if DRAFT_RE.search(text):
            print(f"  skipping {path.name}: marked as draft")
            continue
        week, num, title = match.groups()
        posted = POSTED_RE.search(text)
        date = dt.date.fromisoformat(posted.group(1)) if posted else git_added_date(path)
        lectures.append(dict(path=path, stem=path.stem, week=int(week),
                             num=int(num), title=title.strip(), date=date))
    lectures.sort(key=lambda L: (L["week"], L["num"]))
    return lectures


def latexmk(tex: Path):
    cmd = ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error",
           f"-outdir={BUILD_DIR}", str(tex)]
    result = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stdout[-3000:])
        sys.exit(f"LaTeX failed on {tex.name}")
    return BUILD_DIR / (tex.stem + ".pdf")


def write_full_notes(lectures):
    inputs = "\n".join(f"\\input{{lectures/{L['stem']}}}" for L in lectures)
    tex = f"""% AUTO-GENERATED by build_site.py -- do not edit by hand.
\\documentclass[11pt]{{article}}
\\usepackage{{mech2030notes}}
\\usepackage{{docmute}}   % lets us \\input complete lecture documents
\\begin{{document}}
\\begin{{center}}
  {{\\Huge\\bfseries {COURSE_CODE} Lecture Notes}}\\\\[0.6em]
  {{\\large {COURSE_TITLE} \\textperiodcentered{{}} {TERM}}}\\\\[0.3em]
  \\rule{{\\textwidth}}{{0.8pt}}
\\end{{center}}
\\tableofcontents
{inputs}
\\end{{document}}
"""
    path = ROOT / "full_notes.tex"
    path.write_text(tex, encoding="utf-8")
    return path


def fmt_date(d):
    return d.strftime("%b %-d") if d else ""


def write_index(lectures, has_full):
    weeks = {}
    for L in lectures:
        weeks.setdefault(L["week"], []).append(L)

    sections = []
    for week in sorted(weeks, reverse=True):          # newest week first
        items = []
        for L in weeks[week]:
            date = f'<span class="date">{fmt_date(L["date"])}</span>' if L["date"] else ""
            items.append(
                f'      <li><a href="pdf/{L["stem"]}.pdf">'
                f'<span class="num">Lecture {L["num"]}</span>'
                f'<span class="title">{html.escape(L["title"])}</span></a>{date}</li>')
        sections.append(f'    <section>\n      <h2>Week {week}</h2>\n      <ul>\n'
                        + "\n".join(items) + "\n      </ul>\n    </section>")

    newest = lectures[-1] if lectures else None
    latest = (f'<p class="latest">Latest: <a href="pdf/{newest["stem"]}.pdf">'
              f'Week {newest["week"]}, Lecture {newest["num"]} &mdash; '
              f'{html.escape(newest["title"])}</a></p>') if newest else ""
    full = ('<a class="button" href="pdf/full_notes.pdf">Download all notes (PDF)</a>'
            if has_full else "")
    updated = dt.date.today().strftime("%B %-d, %Y")

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{COURSE_CODE} Lecture Notes</title>
<style>
  :root {{ --bg:#fdfdfb; --fg:#1d1d1f; --muted:#6b6b70; --accent:#9b1c1c;
          --card:#ffffff; --line:#e3e3e0; }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --bg:#16171a; --fg:#ececee; --muted:#9a9aa2; --accent:#f07a7a;
            --card:#1f2024; --line:#303136; }}
  }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; background:var(--bg); color:var(--fg);
         font: 17px/1.55 "Charter","Iowan Old Style","Palatino Linotype",Georgia,serif; }}
  main {{ max-width: 760px; margin: 0 auto; padding: 3rem 1.25rem 4rem; }}
  header {{ border-bottom: 2px solid var(--fg); padding-bottom: 1.25rem; margin-bottom: 2rem; }}
  .code {{ font: 600 0.85rem/1 system-ui,sans-serif; letter-spacing: .12em;
          text-transform: uppercase; color: var(--accent); }}
  h1 {{ font-size: 2.2rem; margin: .4rem 0 .3rem; line-height: 1.15; }}
  .meta {{ color: var(--muted); margin: 0; }}
  .intro {{ margin: 1rem 0 0; }}
  .latest {{ margin: 1rem 0 0; }}
  .button {{ display:inline-block; margin-top:1.1rem; padding:.55rem 1rem;
            border:1.5px solid var(--fg); border-radius:6px; color:var(--fg);
            text-decoration:none; font: 600 .9rem/1.2 system-ui,sans-serif; }}
  .button:hover {{ background: var(--fg); color: var(--bg); }}
  h2 {{ font: 600 .85rem/1 system-ui,sans-serif; letter-spacing:.1em;
       text-transform:uppercase; color:var(--muted); margin: 2rem 0 .6rem; }}
  ul {{ list-style:none; margin:0; padding:0; border-top:1px solid var(--line); }}
  li {{ display:flex; align-items:baseline; gap:1rem; padding:.7rem 0;
       border-bottom:1px solid var(--line); }}
  li a {{ flex:1; color:var(--fg); text-decoration:none; display:flex; gap:1rem; }}
  li a:hover .title {{ color: var(--accent); text-decoration: underline; }}
  .num {{ flex: 0 0 5.5rem; color: var(--muted); font: .9rem/1.6 system-ui,sans-serif; }}
  .date {{ color: var(--muted); font: .85rem/1.6 system-ui,sans-serif; white-space:nowrap; }}
  a {{ color: var(--accent); }}
  footer {{ margin-top: 3rem; color: var(--muted); font: .8rem/1.4 system-ui,sans-serif; }}
</style>
</head>
<body>
<main>
  <header>
    <div class="code">{COURSE_CODE} &middot; {TERM}</div>
    <h1>{COURSE_TITLE} Lecture Notes</h1>
    <p class="meta">{INSTRUCTOR}</p>
    <p class="meta">{DEPARTMENT}</p>
    <p class="meta">{AFFILIATION}</p>
    <p class="intro">{INTRO}</p>
    <p class="intro">{DISCLAIMER}</p>
    {latest}
    {full}
  </header>
{chr(10).join(sections)}
  <footer>Last updated {updated}.</footer>
</main>
</body>
</html>
"""
    (SITE_DIR / "index.html").write_text(page, encoding="utf-8")


def main():
    compile_pdfs = "--no-pdf" not in sys.argv
    print("Finding lectures...")
    lectures = find_lectures()
    print(f"  {len(lectures)} published lecture(s)")

    if SITE_DIR.exists():
        shutil.rmtree(SITE_DIR)
    PDF_DIR.mkdir(parents=True)
    (SITE_DIR / ".nojekyll").touch()   # serve files as-is

    has_full = False
    if compile_pdfs:
        BUILD_DIR.mkdir(exist_ok=True)
        for L in lectures:
            print(f"  compiling {L['path'].name}")
            shutil.copy(latexmk(L["path"]), PDF_DIR / f"{L['stem']}.pdf")
        if lectures:
            print("  compiling full_notes.tex")
            shutil.copy(latexmk(write_full_notes(lectures)), PDF_DIR / "full_notes.pdf")
            has_full = True

    write_index(lectures, has_full)
    print(f"Done. Open {SITE_DIR / 'index.html'} to preview.")


if __name__ == "__main__":
    main()
